import type { UnitDef, UnitType } from '../config/types.js';

/**
 * The full unit catalogue (M3 §1): the three faction scouts shipped in M2, plus the 15 units
 * M3 adds — offence infantry, defence infantry, fast (cavalry analog) and siege for each of
 * the three factions, the faction-neutral Settler, and two wildlife oasis-defender types.
 * Every stat below is copied verbatim from `docs/M3_DESIGN_DECISIONS.md` §1 (draft numbers at
 * classic x1, before `speed.training` — sweepable later by `tools/sim`, never by hand-editing
 * this file). The three existing scouts' `cost` / `baseTrainTimeSec` / `speed` / `scoutAttack`
 * / `scoutDefense` / `foodUpkeepPerHour` values are untouched from M2 — only the new
 * combat/trainability fields were added to them.
 *
 * Nomads get the best scouts (their locked faction identity is "efficient scouts"), Raiders
 * the cheapest and slowest. The wider roster's faction-identity claims from §1 ("Raiders
 * cheapest per attack point and fastest to train; Engineers costliest and hit hardest per
 * unit; Nomads fastest and best per Scrap spent on defence") are a numeric check against this
 * table, reported alongside this step rather than asserted here as an invariant.
 */
export const UNITS: Record<UnitType, UnitDef> = {
  brute: {
    type: 'brute',
    faction: 'raiders',
    role: 'offenseInfantry',
    cost: { scrap: 95, fuel: 15, electronics: 0, food: 25 },
    baseTrainTimeSec: 300,
    speed: 7,
    attack: 40,
    defInfantry: 20,
    defCavalry: 5,
    carry: 60,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 1,
    trainedIn: 'barracks',
  },
  torcher: {
    type: 'torcher',
    faction: 'raiders',
    role: 'defenseInfantry',
    cost: { scrap: 70, fuel: 30, electronics: 10, food: 25 },
    baseTrainTimeSec: 380,
    speed: 7,
    attack: 10,
    defInfantry: 35,
    defCavalry: 60,
    carry: 40,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 1,
    trainedIn: 'barracks',
  },
  lookout: {
    type: 'lookout',
    faction: 'raiders',
    role: 'scout',
    cost: { scrap: 120, fuel: 40, electronics: 20, food: 30 },
    baseTrainTimeSec: 1200,
    speed: 9,
    // Combat stats added in M3 §1: "a scout sitting at home now contributes a little real
    // defence and dies in a real battle, exactly as in Travian." attack is 0 — scouts never
    // attack in regular combat (they are barred from raid/assault armies, §1).
    attack: 0,
    defInfantry: 20,
    defCavalry: 10,
    carry: 0,
    splitClass: 'infantry',
    scoutAttack: 35,
    scoutDefense: 20,
    foodUpkeepPerHour: 1,
    trainedIn: 'barracks',
  },
  biker: {
    type: 'biker',
    faction: 'raiders',
    role: 'fast',
    cost: { scrap: 180, fuel: 230, electronics: 50, food: 60 },
    baseTrainTimeSec: 1150,
    speed: 10,
    attack: 110,
    defInfantry: 45,
    defCavalry: 60,
    carry: 90,
    // The three `fast` units are the only `cavalry` splitClass (§1): their attack counts
    // against a defender's defCavalry weighting when they are the attacker.
    splitClass: 'cavalry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 3,
    trainedIn: 'machineShop',
  },
  ramTruck: {
    type: 'ramTruck',
    faction: 'raiders',
    role: 'siege',
    cost: { scrap: 300, fuel: 180, electronics: 60, food: 80 },
    baseTrainTimeSec: 1800,
    speed: 4,
    attack: 65,
    defInfantry: 30,
    defCavalry: 80,
    carry: 0,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 3,
    trainedIn: 'machineShop',
    // Siege damage (§7): Raiders break gates — high wallDamage, low buildingDamage.
    wallDamage: 8,
    buildingDamage: 3,
  },
  exoTrooper: {
    type: 'exoTrooper',
    faction: 'engineers',
    role: 'offenseInfantry',
    cost: { scrap: 130, fuel: 45, electronics: 30, food: 30 },
    baseTrainTimeSec: 420,
    speed: 7,
    attack: 70,
    defInfantry: 40,
    defCavalry: 25,
    carry: 50,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 1,
    trainedIn: 'barracks',
  },
  bulwark: {
    type: 'bulwark',
    faction: 'engineers',
    role: 'defenseInfantry',
    cost: { scrap: 115, fuel: 35, electronics: 40, food: 30 },
    baseTrainTimeSec: 440,
    speed: 5,
    attack: 30,
    defInfantry: 65,
    defCavalry: 35,
    carry: 20,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 1,
    trainedIn: 'barracks',
  },
  surveyorDrone: {
    type: 'surveyorDrone',
    faction: 'engineers',
    role: 'scout',
    cost: { scrap: 100, fuel: 80, electronics: 60, food: 20 },
    baseTrainTimeSec: 1600,
    speed: 16,
    attack: 0,
    defInfantry: 20,
    defCavalry: 10,
    carry: 0,
    splitClass: 'infantry',
    scoutAttack: 35,
    scoutDefense: 35,
    foodUpkeepPerHour: 1,
    trainedIn: 'barracks',
  },
  armoredQuad: {
    type: 'armoredQuad',
    faction: 'engineers',
    role: 'fast',
    cost: { scrap: 230, fuel: 290, electronics: 95, food: 70 },
    baseTrainTimeSec: 1350,
    speed: 14,
    attack: 120,
    defInfantry: 65,
    defCavalry: 50,
    carry: 100,
    splitClass: 'cavalry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 3,
    trainedIn: 'machineShop',
  },
  railSling: {
    type: 'railSling',
    faction: 'engineers',
    role: 'siege',
    cost: { scrap: 330, fuel: 200, electronics: 170, food: 90 },
    baseTrainTimeSec: 2100,
    speed: 3,
    attack: 75,
    defInfantry: 60,
    defCavalry: 10,
    carry: 0,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 4,
    trainedIn: 'machineShop',
    // Siege damage (§7): Engineers level buildings — high buildingDamage, low wallDamage.
    wallDamage: 3,
    buildingDamage: 9,
  },
  skirmisher: {
    type: 'skirmisher',
    faction: 'nomads',
    role: 'offenseInfantry',
    cost: { scrap: 105, fuel: 35, electronics: 15, food: 30 },
    baseTrainTimeSec: 360,
    speed: 6,
    attack: 65,
    defInfantry: 35,
    defCavalry: 20,
    carry: 45,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 1,
    trainedIn: 'barracks',
  },
  hunterSniper: {
    type: 'hunterSniper',
    faction: 'nomads',
    role: 'defenseInfantry',
    cost: { scrap: 85, fuel: 25, electronics: 20, food: 25 },
    baseTrainTimeSec: 340,
    speed: 7,
    attack: 15,
    defInfantry: 40,
    defCavalry: 50,
    carry: 35,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 1,
    trainedIn: 'barracks',
  },
  falconer: {
    type: 'falconer',
    faction: 'nomads',
    role: 'scout',
    cost: { scrap: 110, fuel: 50, electronics: 30, food: 30 },
    baseTrainTimeSec: 1300,
    speed: 17,
    attack: 0,
    defInfantry: 20,
    defCavalry: 10,
    carry: 0,
    splitClass: 'infantry',
    scoutAttack: 45,
    scoutDefense: 40,
    foodUpkeepPerHour: 1,
    trainedIn: 'barracks',
  },
  duneBuggy: {
    type: 'duneBuggy',
    faction: 'nomads',
    role: 'fast',
    cost: { scrap: 175, fuel: 245, electronics: 55, food: 60 },
    baseTrainTimeSec: 1250,
    speed: 19,
    attack: 90,
    defInfantry: 25,
    defCavalry: 40,
    carry: 75,
    splitClass: 'cavalry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 2,
    trainedIn: 'machineShop',
  },
  ballistaWagon: {
    type: 'ballistaWagon',
    faction: 'nomads',
    role: 'siege',
    cost: { scrap: 295, fuel: 175, electronics: 95, food: 80 },
    baseTrainTimeSec: 1900,
    speed: 3,
    attack: 70,
    defInfantry: 45,
    defCavalry: 10,
    carry: 0,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 3,
    trainedIn: 'machineShop',
    // Siege damage (§7): Nomads are the generalists — balanced wallDamage/buildingDamage.
    wallDamage: 4,
    buildingDamage: 6,
  },
  settler: {
    type: 'settler',
    // `faction: null` + a real `trainedIn` marks "trainable by everybody" (§1): the Settler
    // is the one unit where those two facts combine this way — see the `UnitDef.faction`
    // comment in config/types.ts for the full rationale.
    faction: null,
    role: 'settler',
    cost: { scrap: 900, fuel: 700, electronics: 400, food: 500 },
    baseTrainTimeSec: 4000,
    speed: 5,
    attack: 0,
    defInfantry: 80,
    defCavalry: 80,
    carry: 0,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 1,
    trainedIn: 'commandCenter',
  },
  feralDog: {
    type: 'feralDog',
    // `faction: null` + no `trainedIn` marks "nobody can train this" (§1): wildlife only
    // ever exists as oasis defenders, seeded directly at world genesis (M2a §10).
    faction: null,
    role: 'wildlife',
    // Zeros rather than optional fields keep `calcTrainCost` total, even though nothing
    // ever actually trains a wildlife unit.
    cost: { scrap: 0, fuel: 0, electronics: 0, food: 0 },
    baseTrainTimeSec: 0,
    // Wildlife never move — they hold an oasis, never march. speed: 0 is intentional and
    // must stay that way: `slowestSpeed` / `slowestTroopSpeed` throw on an empty list, so a
    // wildlife-only "army" reaching travel-time math would be a bug at the call site (the
    // movement layer must never construct one), not something this catalogue should paper
    // over with a fake positive speed.
    speed: 0,
    attack: 0,
    defInfantry: 25,
    defCavalry: 20,
    carry: 0,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 0,
  },
  scavengerGang: {
    type: 'scavengerGang',
    // See feralDog above: nobody can train wildlife.
    faction: null,
    role: 'wildlife',
    cost: { scrap: 0, fuel: 0, electronics: 0, food: 0 },
    baseTrainTimeSec: 0,
    // See feralDog above: wildlife never move.
    speed: 0,
    attack: 0,
    defInfantry: 40,
    defCavalry: 30,
    carry: 0,
    splitClass: 'infantry',
    scoutAttack: 0,
    scoutDefense: 0,
    foodUpkeepPerHour: 0,
  },
};
