import { describe, expect, it } from 'vitest';
import { DEFAULT_CONFIG } from '../config/index.js';
import type { BuildingLevels } from '../config/types.js';
import type { Resources } from '../types.js';
import {
  calcNetRates,
  HOUR_MS,
  msUntilAffordable,
  msUntilEmpty,
  msUntilFull,
  settleResources,
  type ResourceState,
} from './resources.js';

const config = DEFAULT_CONFIG;

function resources(partial: Partial<Resources>): Resources {
  return { scrap: 0, fuel: 0, electronics: 0, food: 0, ...partial };
}

// M1a.4b: DEFAULT_CONFIG.upkeep is now set, so Food upkeep is geometric —
// `foodUpkeepWeight * upkeep.ratio ** (level - 1) * speed.production` (ratio 1.58,
// speed.production 5) — instead of the legacy `foodUpkeepWeight * level`. Golden values
// below are hand-recomputed from that formula, not generated by calling it.
describe('calcNetRates', () => {
  it('mirrors gross production for scrap/fuel/electronics and subtracts upkeep for food', () => {
    // scrapYard L1: 25/h scrap, upkeep weight 0.1 -> 0.1 * 1.58^0 * 5 = 0.5.
    // greenhouseFarm L1: 30/h food, upkeep weight 0.
    const buildings: BuildingLevels = [
      { type: 'scrapYard', level: 1 },
      { type: 'greenhouseFarm', level: 1 },
    ];
    expect(calcNetRates(config, buildings)).toEqual(
      resources({ scrap: 25, food: 29.5 }), // 30 gross - 0.5 upkeep
    );
  });

  it('goes negative for food when upkeep outweighs production', () => {
    // commandCenter L1: no production, upkeep weight 0.2 -> 0.2 * 1.58^0 * 5 = 1.
    const buildings: BuildingLevels = [{ type: 'commandCenter', level: 1 }];
    expect(calcNetRates(config, buildings)).toEqual(resources({ food: -1 }));
  });
});

describe('settleResources exactness', () => {
  // scrapYard L1 -> scrap +25/h, upkeep 0.1 * 1.58^0 * 5 = 0.5.
  // commandCenter L1 -> no production, upkeep 0.2 * 1.58^0 * 5 = 1.
  // Net food rate = 0 - (0.5 + 1) = -1.5/h.
  const buildings: BuildingLevels = [
    { type: 'scrapYard', level: 1 },
    { type: 'commandCenter', level: 1 },
  ];
  const start: ResourceState = {
    values: resources({ scrap: 100, fuel: 50, electronics: 10, food: 20 }),
    lastCalcAt: 0,
  };

  it('adds exactly the hourly rate over one hour', () => {
    const next = settleResources(config, buildings, start, HOUR_MS);
    expect(next).toEqual({
      values: resources({ scrap: 125, fuel: 50, electronics: 10, food: 18.5 }),
      lastCalcAt: HOUR_MS,
    });
  });

  it('adds exactly half the hourly rate over half an hour', () => {
    const next = settleResources(config, buildings, start, HOUR_MS / 2);
    expect(next.values.scrap).toBe(112.5);
    expect(next.values.food).toBe(19.25);
  });

  it('adds exactly rate / HOUR_MS over a 1 ms step', () => {
    const next = settleResources(config, buildings, start, 1);
    expect(next.values.scrap).toBeCloseTo(100 + 25 / HOUR_MS, 12);
    expect(next.values.food).toBeCloseTo(20 - 1.5 / HOUR_MS, 12);
  });
});

describe('settleResources purity', () => {
  it('does not mutate state.values or the buildings array', () => {
    const buildings: BuildingLevels = [
      { type: 'scrapYard', level: 1 },
      { type: 'commandCenter', level: 1 },
    ];
    const buildingsSnapshot = buildings.map((b) => ({ ...b }));
    const state: ResourceState = {
      values: resources({ scrap: 100, fuel: 50, electronics: 10, food: 20 }),
      lastCalcAt: 0,
    };
    const valuesSnapshot = { ...state.values };

    settleResources(config, buildings, state, HOUR_MS);

    expect(state.values).toEqual(valuesSnapshot);
    expect(buildings).toEqual(buildingsSnapshot);
  });
});

describe('settleResources cap halting', () => {
  // scrapYard L1 -> 25/h scrap; no warehouse -> cap 4000 (M1a.4b: storage.generalBase
  // raised 800 -> 4000, storage.generalRatio 1.25 -> 1.30, see progressionContract.test.ts).
  const buildings: BuildingLevels = [{ type: 'scrapYard', level: 1 }];

  it('lands exactly on the cap after a very long time, never above it', () => {
    const start: ResourceState = { values: resources({}), lastCalcAt: 0 };
    const next = settleResources(config, buildings, start, 10_000 * HOUR_MS);
    // 25 * 10,000 = 250,000, still vastly exceeds the new 4000 cap, so this still
    // genuinely exercises cap-halting (not just a numeric shift).
    expect(next.values.scrap).toBe(4000);
  });

  it('two consecutive settles across the cap boundary equal one settle over the same span', () => {
    // M1a.4b: durations rescaled (20h/40h -> 100h/200h) so this still genuinely crosses the
    // new 4000 cap: at 100h, 25*100 = 2500 (under); at 200h, 25*200 = 5000 (over, capped).
    const start: ResourceState = { values: resources({}), lastCalcAt: 0 };

    const twoStep1 = settleResources(config, buildings, start, 100 * HOUR_MS);
    const twoStep2 = settleResources(config, buildings, twoStep1, 200 * HOUR_MS);

    const oneStep = settleResources(config, buildings, start, 200 * HOUR_MS);

    expect(twoStep2.values).toEqual(oneStep.values);
    expect(oneStep.values.scrap).toBe(4000); // 25 * 200 = 5000, capped at 4000
  });

  it('does not confiscate a value already above the cap; production is simply halted', () => {
    // M1a.4b: seed rescaled 900 -> 4500 (above the new 4000 cap, same ~1.125x-over-cap
    // relationship the old 900-over-800 seed had) so this still genuinely represents an
    // already-over-cap value.
    const start: ResourceState = { values: resources({ scrap: 4500 }), lastCalcAt: 0 };
    const next = settleResources(config, buildings, start, 10 * HOUR_MS);
    expect(next.values.scrap).toBe(4500);
  });
});

describe('settleResources with a non-advancing or backwards clock', () => {
  const buildings: BuildingLevels = [{ type: 'scrapYard', level: 1 }];
  const start: ResourceState = { values: resources({ scrap: 100 }), lastCalcAt: 1000 };

  it('changes nothing but lastCalcAt when now equals lastCalcAt', () => {
    const next = settleResources(config, buildings, start, 1000);
    expect(next.values).toEqual(start.values);
    expect(next.lastCalcAt).toBe(1000);
  });

  it('changes nothing but lastCalcAt when the clock runs backwards', () => {
    const next = settleResources(config, buildings, start, 500);
    expect(next.values).toEqual(start.values);
    expect(next.lastCalcAt).toBe(500);
  });
});

describe('settleResources negative food', () => {
  // commandCenter L1: no production, upkeep weight 0.2 -> 0.2 * 1.58^0 * 5 = 1/h.
  const buildings: BuildingLevels = [{ type: 'commandCenter', level: 1 }];

  it('loses food over time and floors at 0, never negative', () => {
    const start: ResourceState = { values: resources({ food: 10 }), lastCalcAt: 0 };

    // 10 - 1*5 = 5: under the old rate (-2/h) 5 hours drained exactly to 0; under the new,
    // smaller rate (-1/h) it only reaches 5 — this no longer demonstrates landing exactly on
    // 0, only partial drain (still an exact linear-rate check). "wayPast" below is what
    // demonstrates the actual floor-at-0/never-negative property.
    const partial = settleResources(config, buildings, start, 5 * HOUR_MS);
    expect(partial.values.food).toBe(5);

    const wayPast = settleResources(config, buildings, start, 1000 * HOUR_MS);
    expect(wayPast.values.food).toBe(0);
  });
});

describe('msUntilFull', () => {
  // scrapYard L1 -> 25/h scrap; no warehouse -> cap 4000 (M1a.4b, was 800).
  const buildings: BuildingLevels = [{ type: 'scrapYard', level: 1 }];

  it('matches a hand-computed case', () => {
    const state: ResourceState = { values: resources({ scrap: 100 }), lastCalcAt: 0 };
    // (4000 - 100) / 25 * HOUR_MS = 156 hours
    expect(msUntilFull(config, buildings, state, 'scrap')).toBe(156 * HOUR_MS);
  });

  it('is null at the cap', () => {
    // M1a.4b: seed rescaled 800 -> 4000 (exactly the new cap).
    const state: ResourceState = { values: resources({ scrap: 4000 }), lastCalcAt: 0 };
    expect(msUntilFull(config, buildings, state, 'scrap')).toBeNull();
  });

  it('is null above the cap', () => {
    // M1a.4b: seed rescaled 900 -> 4500 (above the new 4000 cap).
    const state: ResourceState = { values: resources({ scrap: 4500 }), lastCalcAt: 0 };
    expect(msUntilFull(config, buildings, state, 'scrap')).toBeNull();
  });

  it('is null on a zero rate', () => {
    const state: ResourceState = { values: resources({ scrap: 100 }), lastCalcAt: 0 };
    expect(msUntilFull(config, [], state, 'scrap')).toBeNull();
  });

  it('is null on a negative rate (food upkeep exceeding production)', () => {
    const starving: BuildingLevels = [{ type: 'commandCenter', level: 1 }];
    const state: ResourceState = { values: resources({ food: 10 }), lastCalcAt: 0 };
    expect(msUntilFull(config, starving, state, 'food')).toBeNull();
  });

  it('the countdown genuinely reaches the cap when settled that far', () => {
    const state: ResourceState = { values: resources({ scrap: 100 }), lastCalcAt: 0 };
    const eta = msUntilFull(config, buildings, state, 'scrap');
    expect(eta).not.toBeNull();
    const settled = settleResources(config, buildings, state, state.lastCalcAt + (eta ?? 0));
    expect(settled.values.scrap).toBeGreaterThanOrEqual(800 - 1e-9);
  });
});

describe('msUntilEmpty', () => {
  it('is null on a non-negative rate', () => {
    const buildings: BuildingLevels = [{ type: 'scrapYard', level: 1 }];
    const state: ResourceState = { values: resources({ scrap: 100 }), lastCalcAt: 0 };
    expect(msUntilEmpty(config, buildings, state, 'scrap')).toBeNull();
  });

  it('is null when the value is already at or below zero', () => {
    const buildings: BuildingLevels = [{ type: 'commandCenter', level: 1 }];
    const state: ResourceState = { values: resources({ food: 0 }), lastCalcAt: 0 };
    expect(msUntilEmpty(config, buildings, state, 'food')).toBeNull();
  });

  it('matches a hand-computed case on a negative rate', () => {
    // commandCenter L1 -> food rate -1/h (0.2 * 1.58^0 * 5, M1a.4b geometric upkeep).
    const buildings: BuildingLevels = [{ type: 'commandCenter', level: 1 }];
    const state: ResourceState = { values: resources({ food: 10 }), lastCalcAt: 0 };
    // 10 / 1 * HOUR_MS = 10 hours
    expect(msUntilEmpty(config, buildings, state, 'food')).toBe(10 * HOUR_MS);
  });
});

describe('msUntilAffordable', () => {
  it('is 0 when already affordable', () => {
    const buildings: BuildingLevels = [];
    const state: ResourceState = {
      values: resources({ scrap: 100, fuel: 100, electronics: 100, food: 100 }),
      lastCalcAt: 0,
    };
    const cost = resources({ scrap: 50, fuel: 50 });
    expect(msUntilAffordable(config, buildings, state, cost)).toBe(0);
  });

  it('is null when a needed resource has a zero rate', () => {
    const buildings: BuildingLevels = []; // nothing produces scrap
    const state: ResourceState = { values: resources({}), lastCalcAt: 0 };
    const cost = resources({ scrap: 100 });
    expect(msUntilAffordable(config, buildings, state, cost)).toBeNull();
  });

  it('is null when the cost exceeds the resource cap', () => {
    // no warehouse -> cap 4000 for scrap (M1a.4b, was 800).
    // M1a.4b: cost rescaled 900 -> 4500 (above the new 4000 cap).
    const buildings: BuildingLevels = [{ type: 'scrapYard', level: 1 }];
    const state: ResourceState = { values: resources({}), lastCalcAt: 0 };
    const cost = resources({ scrap: 4500 });
    expect(msUntilAffordable(config, buildings, state, cost)).toBeNull();
  });

  it('returns the max-over-resources wait when two resources are short by different amounts', () => {
    // scrapYard L1 -> 25/h scrap; fuelRefinery L1 -> 25/h fuel; both capped at 800 (no warehouse).
    const buildings: BuildingLevels = [
      { type: 'scrapYard', level: 1 },
      { type: 'fuelRefinery', level: 1 },
    ];
    const state: ResourceState = { values: resources({ scrap: 50, fuel: 50 }), lastCalcAt: 0 };
    const cost = resources({ scrap: 200, fuel: 300 });
    // scrap short by 150 -> 6h; fuel short by 250 -> 10h. Max is fuel's 10h.
    expect(msUntilAffordable(config, buildings, state, cost)).toBe(10 * HOUR_MS);
  });

  it('the returned instant really is affordable when fed back through settleResources', () => {
    const buildings: BuildingLevels = [
      { type: 'scrapYard', level: 1 },
      { type: 'fuelRefinery', level: 1 },
    ];
    const state: ResourceState = { values: resources({ scrap: 50, fuel: 50 }), lastCalcAt: 0 };
    const cost = resources({ scrap: 200, fuel: 300 });

    const eta = msUntilAffordable(config, buildings, state, cost);
    expect(eta).not.toBeNull();

    const settled = settleResources(config, buildings, state, state.lastCalcAt + (eta ?? 0) + 1);
    expect(
      settled.values.scrap >= cost.scrap &&
        settled.values.fuel >= cost.fuel &&
        settled.values.electronics >= cost.electronics &&
        settled.values.food >= cost.food,
    ).toBe(true);
  });
});
